import { d as createAstro, c as createComponent, a as addAttribute, r as renderHead, f as renderScript, b as renderTemplate } from '../chunks/astro/server_DPt2DqZq.mjs';
import 'kleur/colors';
import 'html-escaper';
import 'clsx';
/* empty css                                            */
export { renderers } from '../renderers.mjs';

const $$Astro = createAstro("https://jinzhongcun.github.io");
const $$PortfolioBackup = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$PortfolioBackup;
  const pageTitle = "Portfolio - Jin Nakamura";
  return renderTemplate`<html lang="ja" data-astro-cid-5wq4jouw> <head><meta charset="utf-8"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta name="viewport" content="width=device-width"><meta name="generator"${addAttribute(Astro2.generator, "content")}><title>${pageTitle}</title><meta name="description" content="中村仁のプロジェクト実績。研究開発から社会実装まで、技術と社会をつなぐプロジェクト活動。">${renderHead()}</head> <body data-astro-cid-5wq4jouw> <header class="site-header" data-astro-cid-5wq4jouw> <nav class="main-nav" data-astro-cid-5wq4jouw> <div class="nav-logo" data-astro-cid-5wq4jouw> <a href="/" data-astro-cid-5wq4jouw>Jin Nakamura</a> </div> <ul class="nav-menu" data-astro-cid-5wq4jouw> <li data-astro-cid-5wq4jouw><a href="/about" data-astro-cid-5wq4jouw>About</a></li> <li data-astro-cid-5wq4jouw><a href="/news" data-astro-cid-5wq4jouw>News</a></li> <li data-astro-cid-5wq4jouw><a href="/research" data-astro-cid-5wq4jouw>Research</a></li> <li data-astro-cid-5wq4jouw><a href="/activity" data-astro-cid-5wq4jouw>Activity</a></li> <li data-astro-cid-5wq4jouw><a href="/contact" data-astro-cid-5wq4jouw>Contact</a></li> <li data-astro-cid-5wq4jouw><a href="/achievement" data-astro-cid-5wq4jouw>Achievement</a></li> <li data-astro-cid-5wq4jouw><a href="/portfolio" data-astro-cid-5wq4jouw>Portfolio</a></li> <li data-astro-cid-5wq4jouw><a href="#" class="lang-switch" data-astro-cid-5wq4jouw>🌐en</a></li> <li data-astro-cid-5wq4jouw><a href="https://docs.google.com/forms/d/e/1FAIpQLSfkDfbo2Y0Cn71vjd03lPhRq8sn7mlOldBQ2kncj4c2x9hgrA/viewform" target="_blank" class="contact-special" data-astro-cid-5wq4jouw>Contact</a></li> </ul> </nav> </header> <main class="main-content" data-astro-cid-5wq4jouw> <div class="page-header" data-astro-cid-5wq4jouw> <h1 class="page-title" data-astro-cid-5wq4jouw>Portfolio</h1> <p class="page-subtitle" data-astro-cid-5wq4jouw>作品・実績</p> </div> <!-- トピックス --> <section class="topics-section" data-astro-cid-5wq4jouw> <h2 class="section-title" data-astro-cid-5wq4jouw>トピックス</h2> <p class="section-subtitle" data-astro-cid-5wq4jouw>注目プロジェクト・記事を厳選してご紹介</p> <div class="topics-grid" data-astro-cid-5wq4jouw> <!-- GENIAC --> <article class="project-card featured" data-astro-cid-5wq4jouw> <a href="/projects/geniac" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>研究開発</div> <div class="project-period" data-astro-cid-5wq4jouw>2024.02 - 2024.08</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>経済産業省GENIAC 松尾研LLM開発<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>プロジェクトリーダー</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
経済産業省・NEDO主導による国内最大規模の公開型大規模言語モデル開発プロジェクト。チームJINIACリーダーとして30名超のメンバーを統括。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>LLM開発</span> <span class="tag" data-astro-cid-5wq4jouw>チームリーダーシップ</span> <span class="tag" data-astro-cid-5wq4jouw>経産省事業</span> </div> </div> </a> </article> <!-- 未踏 --> <article class="project-card featured" data-astro-cid-5wq4jouw> <a href="/projects/mitou" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>研究開発</div> <div class="project-period" data-astro-cid-5wq4jouw>2024.05 - 2025.03</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>未踏ターゲット事業<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>研究代表者</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
リザバーコンピューティング技術を活用した次世代型自然言語処理モデルの開発。採択金額3,780,000円の研究開発プロジェクト。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>リザバーコンピューティング</span> <span class="tag" data-astro-cid-5wq4jouw>省エネルギーAI</span> <span class="tag" data-astro-cid-5wq4jouw>IPA採択</span> </div> </div> </a> </article> <!-- 脳をつくる --> <article class="project-card" data-astro-cid-5wq4jouw> <a href="/projects/brain-project" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>学術プロジェクト</div> <div class="project-period" data-astro-cid-5wq4jouw>2022.04 - 2023.02</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>脳をつくるプロジェクト2022<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>プロジェクトリーダー</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
公立はこだて未来大学の学際的脳科学プロジェクト。プロジェクトリーダーとして全体統括を担い、世界モデル班リーダーとしてDreamerを用いた自動運転AI開発を主導。実環境での自動走行を実現。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>世界モデル</span> <span class="tag" data-astro-cid-5wq4jouw>Dreamer v1</span> <span class="tag" data-astro-cid-5wq4jouw>モデルベース強化学習</span> <span class="tag" data-astro-cid-5wq4jouw>自動運転</span> <span class="tag" data-astro-cid-5wq4jouw>VAE</span> <span class="tag" data-astro-cid-5wq4jouw>MDN-RNN</span> <span class="tag" data-astro-cid-5wq4jouw>Jetson Nano</span> <span class="tag" data-astro-cid-5wq4jouw>エッジAI</span> <span class="tag" data-astro-cid-5wq4jouw>プロジェクトリーダー</span> </div> </div> </a> </article> <!-- コース相談会 --> <article class="project-card" data-astro-cid-5wq4jouw> <a href="/projects/course-consultation" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>イベント企画</div> <div class="project-period" data-astro-cid-5wq4jouw>2023.11-12</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>メタ学習ラボ コース相談会2023<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>企画立案・代表者</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
学部1年生90名参加の大規模イベント企画・運営。30名超の運営メンバーの統括を担当し、参加者満足度96%を達成。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>イベント企画</span> <span class="tag" data-astro-cid-5wq4jouw>チーム統括</span> <span class="tag" data-astro-cid-5wq4jouw>満足度96%</span> </div> </div> </a> </article> </div> </section> <!-- Works セクション --> <section class="works-section" data-astro-cid-5wq4jouw> <h2 class="section-title" data-astro-cid-5wq4jouw>Works</h2> <p class="section-subtitle" data-astro-cid-5wq4jouw>プロジェクト・活動実績</p> <!-- タグフィルター --> <div class="filter-container" data-astro-cid-5wq4jouw> <div class="filter-buttons" data-astro-cid-5wq4jouw> <button class="filter-btn active" data-filter="all" data-astro-cid-5wq4jouw>すべて</button> <button class="filter-btn" data-filter="research" data-astro-cid-5wq4jouw>研究開発</button> <button class="filter-btn" data-filter="development" data-astro-cid-5wq4jouw>開発</button> <button class="filter-btn" data-filter="education" data-astro-cid-5wq4jouw>教育</button> <button class="filter-btn" data-filter="event" data-astro-cid-5wq4jouw>イベント</button> <button class="filter-btn" data-filter="leadership" data-astro-cid-5wq4jouw>リーダーシップ</button> </div> </div> <div class="works-grid" data-astro-cid-5wq4jouw> <!-- 既存のプロジェクトカードをここに複製 --> <article class="project-card featured" data-tags="research,development,leadership" data-astro-cid-5wq4jouw> <a href="/projects/geniac" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>研究開発</div> <div class="project-period" data-astro-cid-5wq4jouw>2024.02 - 2024.08</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>経済産業省GENIAC 松尾研LLM開発<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>プロジェクトリーダー</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
経済産業省・NEDO主導による国内最大規模の公開型大規模言語モデル開発プロジェクト。チームJINIACリーダーとして30名超のメンバーを統括。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>LLM開発</span> <span class="tag" data-astro-cid-5wq4jouw>チームリーダーシップ</span> <span class="tag" data-astro-cid-5wq4jouw>経産省事業</span> </div> </div> </a> </article> <article class="project-card featured" data-tags="research,development" data-astro-cid-5wq4jouw> <a href="/projects/mitou" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>研究開発</div> <div class="project-period" data-astro-cid-5wq4jouw>2024.05 - 2025.03</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>未踏ターゲット事業<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>研究代表者</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
リザバーコンピューティング技術を活用した次世代型自然言語処理モデルの開発。採択金額3,780,000円の研究開発プロジェクト。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>リザバーコンピューティング</span> <span class="tag" data-astro-cid-5wq4jouw>省エネルギーAI</span> <span class="tag" data-astro-cid-5wq4jouw>IPA採択</span> </div> </div> </a> </article> <article class="project-card" data-tags="research,development,leadership" data-astro-cid-5wq4jouw> <a href="/projects/brain-project" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>学術プロジェクト</div> <div class="project-period" data-astro-cid-5wq4jouw>2022.04 - 2023.02</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>脳をつくるプロジェクト2022<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>プロジェクトリーダー</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
公立はこだて未来大学の学際的脳科学プロジェクト。プロジェクトリーダーとして全体統括を担い、世界モデル班リーダーとしてDreamerを用いた自動運転AI開発を主導。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>世界モデル</span> <span class="tag" data-astro-cid-5wq4jouw>Dreamer v1</span> <span class="tag" data-astro-cid-5wq4jouw>モデルベース強化学習</span> </div> </div> </a> </article> <article class="project-card" data-tags="event,leadership,education" data-astro-cid-5wq4jouw> <a href="/projects/course-consultation" class="card-link" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="project-category" data-astro-cid-5wq4jouw>イベント企画</div> <div class="project-period" data-astro-cid-5wq4jouw>2023.11-12</div> </div> <h3 class="project-title" data-astro-cid-5wq4jouw>メタ学習ラボ コース相談会2023<br data-astro-cid-5wq4jouw><span class="role-mark" data-astro-cid-5wq4jouw>企画立案・代表者</span></h3> <p class="project-summary" data-astro-cid-5wq4jouw>
学部1年生90名参加の大規模イベント企画・運営。30名超の運営メンバーの統括を担当し、参加者満足度96%を達成。
</p> <div class="project-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>イベント企画</span> <span class="tag" data-astro-cid-5wq4jouw>チーム統括</span> <span class="tag" data-astro-cid-5wq4jouw>満足度96%</span> </div> </div> </a> </article> </div> </section> <!-- Insights セクション --> <section class="insights-section" data-astro-cid-5wq4jouw> <h2 class="section-title" data-astro-cid-5wq4jouw>Insights</h2> <p class="section-subtitle" data-astro-cid-5wq4jouw>考察・記事</p> <!-- タグフィルター --> <div class="filter-container" data-astro-cid-5wq4jouw> <div class="filter-buttons" data-astro-cid-5wq4jouw> <button class="filter-btn active" data-filter="all" data-astro-cid-5wq4jouw>すべて</button> <button class="filter-btn" data-filter="research" data-astro-cid-5wq4jouw>研究</button> <button class="filter-btn" data-filter="tech" data-astro-cid-5wq4jouw>技術</button> <button class="filter-btn" data-filter="reflection" data-astro-cid-5wq4jouw>振り返り</button> <button class="filter-btn" data-filter="conference" data-astro-cid-5wq4jouw>学会</button> </div> </div> <div class="insights-grid" data-astro-cid-5wq4jouw> <!-- サンプル記事 --> <article class="insight-card" data-tags="research,tech" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="insight-category" data-astro-cid-5wq4jouw>技術考察</div> <div class="insight-date" data-astro-cid-5wq4jouw>2024.01.15</div> </div> <h3 class="insight-title" data-astro-cid-5wq4jouw>リザバーコンピューティングの可能性と課題</h3> <p class="insight-summary" data-astro-cid-5wq4jouw>
従来のディープラーニングとは異なるアプローチとして注目されるリザバーコンピューティング。その特徴と応用可能性について考察します。
</p> <div class="insight-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>リザバーコンピューティング</span> <span class="tag" data-astro-cid-5wq4jouw>機械学習</span> <span class="tag" data-astro-cid-5wq4jouw>省エネルギー</span> </div> </div> </article> <article class="insight-card" data-tags="reflection,conference" data-astro-cid-5wq4jouw> <div class="card-content" data-astro-cid-5wq4jouw> <div class="card-header" data-astro-cid-5wq4jouw> <div class="insight-category" data-astro-cid-5wq4jouw>学会参加記</div> <div class="insight-date" data-astro-cid-5wq4jouw>2023.12.10</div> </div> <h3 class="insight-title" data-astro-cid-5wq4jouw>NeurIPS 2023参加報告</h3> <p class="insight-summary" data-astro-cid-5wq4jouw>
機械学習分野最高峰の国際会議NeurIPS 2023に参加。最新の研究動向と印象的だった発表について報告します。
</p> <div class="insight-tags" data-astro-cid-5wq4jouw> <span class="tag" data-astro-cid-5wq4jouw>NeurIPS</span> <span class="tag" data-astro-cid-5wq4jouw>国際会議</span> <span class="tag" data-astro-cid-5wq4jouw>研究動向</span> </div> </div> </article> </div> </section> </main> <footer class="site-footer" data-astro-cid-5wq4jouw> <p data-astro-cid-5wq4jouw>&copy; 2024 Jin Nakamura. All rights reserved.</p> </footer>  ${renderScript($$result, "/mnt/c/Users/jinsm/jinnakamura/src/pages/portfolio_backup.astro?astro&type=script&index=0&lang.ts")} </body> </html>`;
}, "/mnt/c/Users/jinsm/jinnakamura/src/pages/portfolio_backup.astro", void 0);

const $$file = "/mnt/c/Users/jinsm/jinnakamura/src/pages/portfolio_backup.astro";
const $$url = "/jinnakamura-public/portfolio_backup";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$PortfolioBackup,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
